name: Coverage Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Compile contracts
        run: npm run compile

      - name: Run coverage
        run: npm run test:coverage

      - name: Check coverage thresholds
        run: |
          echo "Checking coverage thresholds..."
          node -e "
          const coverage = require('./coverage/coverage-summary.json');
          const total = coverage.total;

          const thresholds = {
            statements: 90,
            branches: 85,
            functions: 90,
            lines: 90
          };

          let failed = false;

          for (const [metric, threshold] of Object.entries(thresholds)) {
            const actual = total[metric].pct;
            console.log(\`\${metric}: \${actual}% (threshold: \${threshold}%)\`);
            if (actual < threshold) {
              console.error(\`❌ \${metric} coverage \${actual}% is below threshold \${threshold}%\`);
              failed = true;
            } else {
              console.log(\`✅ \${metric} coverage \${actual}% meets threshold\`);
            }
          }

          if (failed) {
            process.exit(1);
          }
          " || true

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-coverage

      - name: Comment PR with coverage
        if: github.event_name == 'pull_request'
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          lcov-file: ./coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
